# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "fedora19"
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  config.vm.network :forwarded_port, guest: 8081, host: 8080
  config.vm.provision :shell, :privileged => false, :path => "bootstrap.sh"

  config.vm.synced_folder "./", "/vagrant"

  config.vm.provider :virtualbox do |vb|
  #   vb.gui = true
  #   vb.customize ["modifyvm", :id, "--memory", "768"]
      vb.name = "v3spa_builder19"
  end

end
